### ISSUE TITLE
No AI

### ISSUE THREAD

**Issue by ghost** [Agnishom/ChainReactionAI#1]
Looks like there is no AI implemented. It just randomly plays it.

**Comment by Agnishom** [comment]
I tried to make an elementary implementation of minimax [here](https://github.com/Agnishom/ChainReactionAI/blob/master/minimax.py)

**Comment by ghost** [comment]
Thanks for your hard work buddy :D

**Comment by Agnishom** [comment]
Thanks. I have marked the issue as closed
